-- Run this entire file once in Supabase > SQL Editor.
create table if not exists public.settings (
  id integer primary key check (id = 1), site_name text not null, tagline text not null,
  ticker text not null, whatsapp_number text not null, address text not null,
  hours text not null, updated_at timestamptz not null default now()
);
create table if not exists public.services (
  id text primary key, icon text not null default '📄', title text not null,
  tagline text not null default '', description text not null default '', youtube text not null default '',
  documents text[] not null default '{}', sort_order integer not null default 0
);
create table if not exists public.master_documents (
  id bigint generated by default as identity primary key, name text unique not null, sort_order integer not null default 0
);
create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.settings enable row level security;
alter table public.services enable row level security;
alter table public.master_documents enable row level security;
alter table public.app_admins enable row level security;

create or replace function public.is_app_admin() returns boolean
language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.app_admins where user_id = auth.uid()) $$;

drop policy if exists "public read settings" on public.settings;
drop policy if exists "public read services" on public.services;
drop policy if exists "public read documents" on public.master_documents;
drop policy if exists "admin settings" on public.settings;
drop policy if exists "admin services" on public.services;
drop policy if exists "admin documents" on public.master_documents;
create policy "public read settings" on public.settings for select to anon, authenticated using (true);
create policy "public read services" on public.services for select to anon, authenticated using (true);
create policy "public read documents" on public.master_documents for select to anon, authenticated using (true);
create policy "admin settings" on public.settings for all to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
create policy "admin services" on public.services for all to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
create policy "admin documents" on public.master_documents for all to authenticated using (public.is_app_admin()) with check (public.is_app_admin());

insert into public.settings(id,site_name,tagline,ticker,whatsapp_number,address,hours) values
(1,'BGI Cybercafe','Aapke sarkari documents, ek hi jagah','New services are available — contact us on WhatsApp.','91XXXXXXXXXX','Akola, Maharashtra','Mon – Sat, 9:00 AM – 8:00 PM')
on conflict(id) do nothing;

insert into public.master_documents(name,sort_order) values
('Aadhar Card',1),('PAN Card',2),('Voter ID (Election Card)',3),('Passport',4),('Passport Size Photo',5),
('Signature (White Background)',6),('SSC Marksheet',7),('HSC Marksheet',8),('Caste Certificate',9),
('Domicile Certificate',10),('Income Certificate',11),('Bank Passbook',12),('Admission Receipt',13),
('School Leaving Certificate',14),('Internship Certificate',15),('Birth Certificate',16),('Ration Card',17),
('Address Proof (Light / Water Bill)',18),('Mobile Number & Email ID',19),('Rent Agreement / NOC from Landlord',20),
('Business Registration Proof',21),('Shop Photo with Signboard',22),('Affidavit (Notarized)',23),
('Newspaper Publication Copy',24),('Police Verification Form',25),('Salary Slip / Self-Declaration',26)
on conflict(name) do nothing;

insert into public.services(id,icon,title,tagline,description,youtube,documents,sort_order) values
('fssai','🍽️','FSSAI License Registration','Food business license','Get your food business registered with FSSAI — required for any shop, cart, restaurant or home kitchen selling food.','',array['Aadhar Card','PAN Card','Passport Size Photo','Address Proof (Light / Water Bill)','Rent Agreement / NOC from Landlord','Shop Photo with Signboard','Business Registration Proof','Mobile Number & Email ID'],1),
('udyam','🏭','Udyam Registration (MSME)','Small business / MSME','Register your business under Udyam (MSME) to unlock government schemes, loans and subsidies.','',array['Aadhar Card','PAN Card','Bank Passbook','Address Proof (Light / Water Bill)','Business Registration Proof','Mobile Number & Email ID'],2),
('food-license','🧾','Food License','State food license','State-level food license for small eateries, tiffin services and food stalls.','',array['Aadhar Card','PAN Card','Passport Size Photo','Address Proof (Light / Water Bill)','Shop Photo with Signboard','Rent Agreement / NOC from Landlord'],3),
('character-certificate','🛡️','Character Certificate','Police / Tehsil verification','Character certificate needed for jobs, visas and higher education admissions.','',array['Aadhar Card','PAN Card','Passport Size Photo','Address Proof (Light / Water Bill)','Affidavit (Notarized)','Police Verification Form'],4),
('gazette-certificate','📜','Gazette Certificate (Name Change)','Official name change','Legally change or correct your name, surname or spelling through the official Gazette process.','',array['Aadhar Card','PAN Card','Passport Size Photo','Affidavit (Notarized)','Newspaper Publication Copy','Birth Certificate'],5),
('caste-certificate','📋','Caste Certificate','SC / ST / OBC / EWS','Caste certificate for admissions, jobs and government scheme benefits.','',array['Aadhar Card','PAN Card','SSC Marksheet','School Leaving Certificate','Domicile Certificate','Passport Size Photo','Ration Card','Affidavit (Notarized)'],5),
('domicile-certificate','🏠','Domicile Certificate','Residence proof','Proof of permanent residence, required for admissions, jobs and scholarships.','',array['Aadhar Card','SSC Marksheet','School Leaving Certificate','Birth Certificate','Ration Card','Address Proof (Light / Water Bill)','Passport Size Photo'],6),
('income-certificate','💰','Income Certificate','Annual family income proof','Income certificate for scholarships, fee concessions and government scheme applications.','',array['Aadhar Card','PAN Card','Bank Passbook','Ration Card','Salary Slip / Self-Declaration','Address Proof (Light / Water Bill)'],7)
on conflict(id) do nothing;

-- IMPORTANT: First create your user in Authentication > Users > Add user.
-- Then replace the email below and run ONLY this final statement:
-- insert into public.app_admins(user_id)
-- select id from auth.users where email = 'YOUR_ADMIN_EMAIL@example.com'
-- on conflict(user_id) do nothing;
